### PR TITLE
Switched database to PostgreSQL and Dockerized Django and React

### PR DESCRIPTION
**Pull request by brianzhouzc**
Everything should be running in Docker now, which will make running the entire tech stack much easier.

To start, first, install Docker on your system. If you are using Windows then install the Docker Desktop application from: https://www.docker.com/products/docker-desktop

Then, simply cd into the root directory and run:
`docker-compose build`
This will build all the images for docker. This should take ~3min, but might take longer depending on your network speed.

After building the images, run:
`docker-compose up`
This will start all the containers. Visit localhost:8000 to view the website.

**If you are running containers for the first time, you need to initialize the PostgreSQL database.**
**To do so, first use `docker-compose up` to start all containers, then open the Docker desktop app and navigate to Containers/Apps -> skillsanalysis -> postgres -> CLI**
**A console window will show up, type in `./manage.py migrate --run-syncdb` and execute the command**
**After that's done, close the cli window. Navigate to the original console you used to lanch docker and press ctrl+c to terminate the containers. Then use `docker-compose up` to restart everything**

Note: You only need to build docker images once, unless you added new dependencies to React.

### CODE REVIEW

**Comment by brianzhouzc** [comment]
Let me know if you encounter any issue when running the docker containers, I'm happy to help out

**Review by SanaBob — APPROVED** [review]
lgtm

**Review by OKThomas1 — APPROVED** [review]
Got it up and running, but opening a CLI for the postgres container and running `./manage.py migrate --run-syncdb` didn't work, I had to open a CLI for the django container and run `python manage.py migrate`, the `./manage.py migrate --run-syncdb` command didn't work on the django container CLI either

**Comment by bohuie** [comment]
I see the instructions in the comments... Can you update the README as well as part of this PR?

**Comment by brianzhouzc** [comment]
> Got it up and running, but opening a CLI for the postgres container and running `./manage.py migrate --run-syncdb` didn't work, I had to open a CLI for the django container and run `python manage.py migrate`, the `./manage.py migrate --run-syncdb` command didn't work on the django container CLI either

Thanks for the feedback, I'll correct the instructions and put them into README

**Pull request merged**
