### PR TITLE
Feat user model

### PR DESCRIPTION
**Pull request by liewshanhong**

### CODE REVIEW

**Comment by brianzhouzc** [comment]
This pull request contains commits from #12 and #11 , we should merge those first before we proceed with this pull request.

**Comment by OKThomas1** [comment]
I made it so logging in only redirects you to the questions page if the user does not have a profile, otherwise it redirects you to the home page, and so users can only view their profile if they have one, otherwise it redirects you to the questions page. I also added a related_name of "profile" to the user field of the profile model, so we can do request.user.profile to get the user's profile in django.

**Comment by OKThomas1** [comment]
Made it so users can resubmit the questions and it will update their profile.

**Review by OKThomas1 — APPROVED** [review]
Everything seems to be working as expected.

**Review by brianzhouzc — APPROVED** [review]

**Comment by brianzhouzc** [comment]
Working as expected. I have to change the logic of how the profile is being checked/created since it's throwing an error. Everything working fine now.

**Pull request merged**
